### ISSUE TITLE
3 unittests failed

### ISSUE THREAD

**Issue by Shreeshrii** [tmbdev/hocr-tools#122]
```
(venv) ubuntu@tesseract-ocr:~/hocr-tools$ ./test/tsht
# Testing ./hocr-check/test-hocr-check.tsht
1..11
ok 1 - Check from filename
ok 2 - Check from stdin
# ./ancestor: valid examples
ok 3 - 'hocr-check ./ancestor/ok-par.html' (failed: 0)
ok 4 - 'hocr-check ./ancestor/ok-line.html' (failed: 0)
ok 5 - 'hocr-check ./ancestor/ok-carea.html' (failed: 0)
# ./ancestor: invalid examples
ok 3 - 'hocr-check ./ancestor/notok-line.html' (failed: 1)
ok 4 - 'hocr-check ./ancestor/notok-carea.html' (failed: 1)
ok 5 - 'hocr-check ./ancestor/notok-par.html' (failed: 1)
# ./meta: valid examples
ok 3 - 'hocr-check ./meta/ok-system.html' (failed: 0)
# ./meta: invalid examples
ok 3 - 'hocr-check ./meta/notok-typo.html' (failed: 1)
ok 4 - 'hocr-check ./meta/notok-system.html' (failed: 1)
# Testing ./hocr-combine/test-hocr-combine.tsht
1..2
ok 1 - Executed: hocr-combine ../testdata/sample.html ../testdata/sample.html
ok 2 - check whether number ocr_lines in self-combined result is doubled
# Testing ./hocr-eval-geom/hocr-eval-geom.tsht
1..3
ok 1 - Executed: hocr-eval-geom ../testdata/sample.html ../testdata/sample.html
ok 2 - Executed: hocr-eval-geom -e ocr_line -o 0.05 -c 0.88 ../testdata/tess.hocr ../testdata/sample.html
ok 3 - Matches '\(0, 0, 0.0, ': '(0, 0, 0.0, 37) (0, 0, 0.0, 37)'
# Testing ./hocr-eval/hocr-eval.tsht
1..2
ok 1 - Executed: hocr-eval ../testdata/sample.html ../testdata/sample.html
not ok 2 - Failed: hocr-eval -d -v ../testdata/tess.hocr ../testdata/sample.html
---
diag: |
overlap 52041 true_bbox (470, 528, 1383, 585)
1 Down the Rabbit-Hole
1 Down the Rabbit-Hole
overlap 85330 true_bbox (464, 651, 2074, 704)
Alice was beginning to get very tired of sitting by her sister on the bank,
Alice was beginning to get very tired of sitting by her sister on the bank,
overlap 83824 true_bbox (464, 711, 2076, 763)
and of having nothing to do: once or twice she had peeped into the book her
and of having nothing to do: once or twice she had peeped into the book her
overlap 80600 true_bbox (463, 773, 2075, 823)
Traceback (most recent call last):
File "/usr/local/bin/hocr-eval", line 4, in <module>
__import__('pkg_resources').run_script('hocr-tools==1.2.0', 'hocr-eval')
File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
self.require(requires)[0].run_script(script_name, ns)
File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
exec(script_code, namespace, namespace)
File "/usr/local/lib/python2.7/dist-packages/hocr_tools-1.2.0-py2.7.egg/EGG-INFO/scripts/hocr-eval", line 227, in <module>

UnicodeEncodeError: 'ascii' codec can't encode character u'‘' in position 67: ordinal not in range(128)
...

# Testing ./hocr-eval-lines/hocr-eval-lines.tsht
1..4
ok 1 - Executed: hocr-eval-lines -v ../testdata/sample.txt ../testdata/sample.html
ok 2 - Matches 'ocr_errors 7': 'segmentation_errors 0<LF>ocr_errors 7'
ok 3 - Matches 'segmentation_errors 0': 'segmentation_errors 0<LF>ocr_errors 7'
ok 4 - Not like '\('segmentation_errors'': 'string'
# Testing ./hocr-extract-images/test-hocr-extract-images.tsht
1..10
# ocr_page argument
ok 1 - Executed: hocr-extract-images -p page-%03d.png -b ../testdata -e ocr_page ../testdata/tess.hocr
ok 2 - ocr_page: number of images == 1
ok 3 - ocr_page: number of texts == 1
# ocr_page stdin
ok 4 - ocr_page: number of images == 1
ok 5 - ocr_page: number of texts == 1
# ocr_line argument
ok 6 - Executed: hocr-extract-images -p line-%03d.png -b ../testdata -e ocr_line ../testdata/tess.hocr
ok 7 - ocr_line: number of images == 37
ok 8 - ocr_line: number of texts == 37
# ocr_line stdin
ok 9 - ocr_line: number of images == 37
ok 10 - ocr_line: number of texts == 37
# ocrx_word argument
ok 11 - Executed: hocr-extract-images -p word-%03d.png -b ../testdata -e ocrx_word ../testdata/tess.hocr
ok 12 - ocrx_word: number of images == 503
ok 13 - ocrx_word: number of texts == 503
# ocrx_word stdin
ok 14 - ocrx_word: number of images == 503
ok 15 - ocrx_word: number of texts == 503
ok 16 - Indeed 503 words in sample
# Testing ./hocr-lines/hocr-lines.tsht
1..3
Traceback (most recent call last):
  File "/usr/local/bin/hocr-lines", line 4, in <module>
    __import__('pkg_resources').run_script('hocr-tools==1.2.0', 'hocr-lines')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1511, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/hocr_tools-1.2.0-py2.7.egg/EGG-INFO/scripts/hocr-lines", line 22, in <module>

UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 67: ordinal not in range(128)
not ok 1 - hocr-lines
not ok 2 - ./tess.lines ('37' != '3')
ok 3 - check first line
after
# Running function after for hocr-lines.tsht
# Testing ./hocr-merge-dc/hocr-merge-dc.tsht
1..4
ok 1 - Command succeeded
ok 2 - Matches 'name='DC.title' content='Alice im Wonderland'': '<?xml version="1.0" encoding="UTF-8"?><LF><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" <LF>    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> <LF><html xmlns="http://www.'
ok 3 - Not like 'name='DC.title' content='UKOLN'': 'string'
ok 4 - Matches 'name="DC.title" content="UKOLN"': '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><LF><?xml version="1.0" encoding="UTF-8"??><LF><html xmlns="http://www.w3.org/1'
# Testing ./hocr-pdf/test-hocr-pdf.tsht
ok 1 - Executed: wget --quiet http://digi.bib.uni-mannheim.de/fileadmin/digi/445442158/tess/445442158_0126.hocr
ok 2 - Executed: wget --quiet http://digi.bib.uni-mannheim.de/fileadmin/digi/445442158/max/445442158_0126.jpg
ok 3 - Not empty file: 445442158_0126.pdf
ok 4 - Executed: pdfgrep tribunali 445442158_0126.pdf
1..4
# Testing ./hocr-split/test-hocr-split.tsht
1..4
ok 1 - Executed: hocr-split test.hocr test-%003d.hocr
ok 2 - two files were produced
ok 3 - one page in test-001.hocr
ok 4 - one page in test-002.hocr
ok 5 - one xml:lang= only, #58
ok 6 - one xmlns= only, #58
# Testing ./hocr-wordfreq/hocr-wordfreq.tsht
1..4
ok 1 - Executed: hocr-wordfreq ../testdata/sample.html
ok 2 - Executed: hocr-wordfreq -i -n 30 ../testdata/sample.html
ok 3 - Matches '23\s*the': '23          the'
ok 4 - Matches '24\s*the': '24          the'
# Testing ./smoke.tsht
ok 1 - Executed: hocr-check --help
ok 2 - Executed: hocr-check -h
ok 3 - Executed: hocr-combine --help
ok 4 - Executed: hocr-combine -h
ok 5 - Executed: hocr-eval --help
ok 6 - Executed: hocr-eval -h
ok 7 - Executed: hocr-eval-geom --help
ok 8 - Executed: hocr-eval-geom -h
ok 9 - Executed: hocr-eval-lines --help
ok 10 - Executed: hocr-eval-lines -h
ok 11 - Executed: hocr-extract-g1000 --help
ok 12 - Executed: hocr-extract-g1000 -h
ok 13 - Executed: hocr-extract-images --help
ok 14 - Executed: hocr-extract-images -h
ok 15 - Executed: hocr-lines --help
ok 16 - Executed: hocr-lines -h
ok 17 - Executed: hocr-merge-dc --help
ok 18 - Executed: hocr-merge-dc -h
ok 19 - Executed: hocr-pdf --help
ok 20 - Executed: hocr-pdf -h
ok 21 - Executed: hocr-split --help
ok 22 - Executed: hocr-split -h
1..22
# Failed 3 tests

```

**Comment by Shreeshrii** [comment]
not ok 2 - Failed: hocr-eval -d -v ../testdata/tess.hocr ../testdata/sample.html

UnicodeEncodeError: 'ascii' codec can't encode character u'‘' in position 67: ordinal not in range(128)


UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 67: ordinal not in range(128)
not ok 1 - hocr-lines
not ok 2 - ./tess.lines ('37' != '3')

**Comment by zuphilip** [comment]
@Shreeshrii Try to run
```
PYTHONIOENCODING=UTF-8 ./test/tsht
```
instead. Any difference?
